spec/dummy/app/commands/users.rb
spec/dummy/spec/integration/user_commands_spec.rb

I was following http://rom-rb.org/tutorials/rails/ tutorial and found issue when trying to implement `destroy` action in my rails app.
Running: `users.try { delete(:by_name, 'Piotr') }`
throws:
```
NoMethodError:
undefined method `size' for #<#<Class:0x007fd82aa522b0>:0x007fd82d3f7d68>
```
I don't know if this is bug in rom-rails or in rom, but definitely when fixed it would be nice to have it covered here.

failing spec demonstraing not working delete command

---

.travis.yml

`sudo: false` enables docker containers: http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
`cache: bundler` caches bundled gems between builds

speed up builds on Travis

---

lib/rom/model.rb
spec/model_spec.rb

Ensures attributes are coerced to either the specified type or nil.
As an aside, it would be great if Virtus supported setting the required option on a per model basis, so we didn't have to override `attribute`. Something like `include Virtus.model(strict: true, required: false)`.

Use Virtus in strict mode to ensure input is coerced

---

lib/rom/rails/configuration.rb
lib/rom/rails/railtie.rb
spec/dummy/spec/integration/logger_spec.rb
spec/dummy/spec/integration/user_model_mapping_spec.rb
spec/spec_helper.rb

Initializers like the following can now be used to configure repositories:
```ruby
Rails.application.configure do |app|
app.config.rom.repos[:yaml] = {uri: 'yaml:///config'}
end
```

Improve configuration API and support for initializers

---

lib/rom/rails/active_record/configuration.rb
lib/rom/rails/configuration.rb
lib/rom/rails/railtie.rb
spec/lib/active_record/configuration_spec.rb

I'm starting to tackle rom-rb/rom#92. Support for `ENV['DATABASE_URI']` will come for free. We're moving `ROM::Config` to `rom-rails` as discussed.

Make inheriting configuration from ActiveRecord more solid.

---

lib/rom/model.rb
spec/dummy/spec/integration/user_params_spec.rb

Fixes #132
Added a `#timestamps` method so that we get two attributes with default
values:
1. `created_at`
2. `updated_at`
Per issue #132, they are `DateTime` instances and their default value is
a proc returning `DateTime.now`.

Reduce duplication with `#timestamps` method

---

lib/rom/rails/model/params.rb
spec/dummy/spec/integration/user_params_spec.rb

Previously, `.timestamps` had zero-arity.  It created `created_at`
and `updated_at` timestamps.
This change makes it so you can specify one or more custom timestamps.
See discussion at rom-rb/rom-rails#19

Change `.timestamps` to have variable arity

---

lib/rom/rails/model/form.rb
spec/unit/form_spec.rb

A number of form-building libraries, such as simple_form and formtasic,
depend on the active-model errors interface.  They expect Errors to
always be present, never nil,  and to return an empty array for specific
attribute errors.
This bounces forward an empty errors object, when no errors are found in
the result.
Note:  I've only added unit tests for the base, pre-save case.  the
integration specs seem to have driven the change to the success? method
without needing any additional specs

form.errors may return a blank ActiveModel::Errors object

---

lib/rom/rails/model/form.rb
spec/unit/form_spec.rb
spec/unit/validator_spec.rb

This will run the validations without attempting a database
modification; useful for workflows that need to ensure
provided data is good without immediately saving to the datastore.
This relies on the AM#validate method, which is an alias for valid.  The spec on that method ensures that the api doesn't break out from underneath us.  (Okay, so I was surprised when the spec passed before I did anything.  TIL, ActiveModel::Validations defines `validate`)

Add form#validate! method to run validations

---

lib/rom/rails/model/validator/uniqueness_validator.rb

In a project which hasn't already required `active_model` elsewhere `ActiveModel::EachValidator` can be undefined by the time rom-rails is required.  Adding this require stops that from being a problem.

Added explicit require of active_model

---

lib/rom/rails/railtie.rb

Avoids `uninitialized constant` when ActiveRecord is not used.
Exact error was:
```
/lib/rom/rails/active_record/configuration.rb:27:in `call': uninitialized constant ActiveRecord (NameError)
```

Look for ActiveRecord in global namespace

---

lib/generators/rom/mapper/templates/mapper.rb.erb
spec/lib/generators/mapper_generator_spec.rb

This way, `ROM.finalize` will always be able to build the mapper registry properly on Rails startup, and users can `rails g` as many ROM objects as they like without having to modify them by hand.

Always include a live relation link in generated mappers

---

lib/rom/rails/model/form/class_interface.rb
spec/unit/form_spec.rb

ref rom-rb/rom#184
This allows for a subclass of a form to use the `input` and `validation` blocks to extend the form definition, without throwing out the existing form information.
Note that  11ac4c1 changes existing behavior by squelching an error that was being thrown.  Discussion welcome.

Child forms inherit attributes

---

lib/rom/rails/active_record/configuration.rb
spec/lib/active_record/configuration_spec.rb

I tested the `ROM::Rails::ActiveRecord::Configuration.build` method with what `::ActiveRecord::Base.configurations.fetch(::Rails.env)` returns as a config for the mysql2 adapter.

ensure AR Configuration return correct mysql2 uri and options

---

README.md

This PR will fix the URLs of rom-rb oficial website. (The ToDo tutorial for rails was removed from the website. Don't know if it would be nice to put it again on the site)
Thanks,
:beers:

Fix ROM-Rails resources URLs on README

---

lib/generators/rom/mapper_generator.rb
spec/lib/generators/mapper_generator_spec.rb

This PR will fix the Mapper generator to fix the `register_as` line.
Closes #54 
Thanks so much
:beers:

Fix Mapper generator register_as line

---

lib/rom/rails/configuration.rb
lib/rom/rails/railtie.rb
spec/dummy/config/initializers/rom.rb
spec/dummy/lib/additional_app/app/commands/create_additional_task.rb
spec/integration/initializer_spec.rb

I faced this problem when tried to use rom-rails inside Rails engine. It occurred that relations, mappers and commands are not being autoloaded from engine to the main app. Here I suggest adding this functionality.

Multiple auto_registration paths

---

.travis.yml
Gemfile
lib/rom/rails/model/form.rb
rom-rails.gemspec
spec/dummy/config/application.rb

Allow rom-rails to work with rails5.
The warnings mostly seem to be centered around a change to ActionController::Parameters, wherin it is no longer considered to be a Hash, and considers `to_h` to be unsafe ... 
```
DEPRECATION WARNING: Method to_hash is deprecated and will be removed in Rails 5.1, as `ActionController::Parameters` no longer inherits from hash. Using this deprecated behavior exposes potential security problems. If you continue to use this method you may be creating a security vulnerability in your app that can be exploited. Instead, consider using one of these documented methods which are not deprecated: http://api.rubyonrails.org/v5.0.0/classes/ActionController/Parameters.html (called from new at /home/flip/src/rom-rb/rom-rails/lib/rom/rails/model/form.rb:96)
```
To be …

[WIP] Use rails5

---

lib/rom/rails/model/form.rb
lib/rom/rails/model/form/class_interface.rb
spec/dummy/app/commands/create_task_with_validations.rb
spec/integration/form_with_command_validation_spec.rb
spec/unit/form_spec.rb

This moves the point of validation from "injected into command" to occurring within the form itself, solely.
This accounts for the deprecation warning now raised by ROM-core, however there is a single expected deprecation warning from the tests, where the 'existing' behavior is explicitly supported, in the form of copying command validation errors over into the form's error object. This _only_ applies if the application is still explicitly assgning command validations; when that behavior is removed from core, the behavior in cd253a6 should be  reverted.

Move validations

---

lib/generators/rom/commands/templates/create.rb.erb
lib/generators/rom/commands/templates/delete.rb.erb
lib/generators/rom/commands/templates/update.rb.erb
lib/generators/rom/commands_generator.rb
spec/lib/generators/commands_generator_spec.rb

A few tweaks to modernize the command generators:
Flatten the generated directory structure, so its less confused.
Provide a hint for overriding the execute method, so users will have some guidance on _where_ to go
Remove the hint for the deprecated validator method

Update command generators

---

rom-rails.gemspec

Charlatan was removed in this commit
https://github.com/rom-rb/rom-rails/commit/2613a1ec64f34bf9bce98ceaacfecb1644d6da5e#diff-8d714453b1415ca9883197befff1600aL1

Remove charlatan runtime dependency

---

lib/rom/rails/railtie.rb

When running ROM queries in `rails c`, we should see the SQL it is executing, similar to how Active Record does it.
I've borrowed some lines here for `rom-rails` to use from active_record's codebase. I don't think they'll mind.
```
irb(main):002:0> repo.create(name: "omg")
ROM[postgres] (0.2ms)  SET standard_conforming_strings = ON
ROM[postgres] (0.2ms)  SET client_min_messages = 'WARNING'
ROM[postgres] (0.2ms)  SET DateStyle = 'ISO'
ROM[postgres] (4.4ms)  INSERT INTO "projects" ("name") VALUES ('omg') RETURNING "projects"."id", "projects"."name"
=> #<Project:0x00007fe45f3b6438 @id=12, @name="omg">
```

Broadcast ROM output to STDOUT during `rails c`

---

lib/generators/rom.rb
lib/generators/rom/commands/templates/create.rb.erb
lib/generators/rom/commands/templates/delete.rb.erb
lib/generators/rom/commands/templates/update.rb.erb
lib/generators/rom/commands_generator.rb
lib/generators/rom/relation_generator.rb
spec/lib/generators/commands_generator_spec.rb

comands generator should also use default gateway's adapter
Pull the discovery out to the base class.  If there is no default gateway, don't make any assumptions
fixes #92

Use default adapter

---

lib/rom/rails/active_record/configuration.rb
spec/lib/active_record/configuration_spec.rb

Sequel expects valid connection string (URI) which is not met with special characters in password or username.
See https://github.com/jeremyevans/sequel/issues/1361 for details.
I am getting:
```
....
4: from /Volumes/Data/Users/cervajz/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.13.0/lib/sequel/core.rb:121:in `connect'
3: from /Volumes/Data/Users/cervajz/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.13.0/lib/sequel/database/connecting.rb:34:in `connect'
2: from /Volumes/Data/Users/cervajz/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/common.rb:237:in `parse'
1: from /Volumes/Data/Users/cervajz/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
/Volumes/Data/Users/cervajz/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split': bad …
```

Escape username and password for special characters

---

lib/rom/rails/railtie.rb

ActiveRecord creates its own console output to STDERR and STDOUT and
it looks like the #logger_outputs_to? does not catch that. The result is
is having the log messages twice in rails console.
More info:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/railtie.rb#L58

Do not output log messages twice when ActiveRecord present

---

lib/rom/rails/active_record/configuration.rb
lib/rom/rails/active_record/uri_builder.rb
lib/rom/rails/railtie.rb
spec/lib/active_record/configuration_spec.rb

Attempt to cleanly handle the new database configuration structures in Rails6.
Rails6 introduces a new configuration object, rather than keeping just a hash of connection options.  Let's verify that we can use that object.
This should handle the base, legacy case for configuration keys, and fix #104.  Handling the new multiple-database configuration is going to take another few refinements.

Handle rails6 config

---

README.md

There's a redirect set up, so it goes to the latest version.
I'll look to address #108 when I actually do configue rom-rails soon.

Fix link to guide

---

.travis.yml
Gemfile
rom-rails.gemspec

Update gemspecs to allow rails 6.1.  Add to the build matrix
partially cherrypicked off #116

Allow rails6.1

---

lib/rom/rails/configuration.rb
lib/rom/rails/railtie.rb

When developing, file change causes ROM-Rails to rebuild the container, this leads to a database reload.
It works well with a small database, but when you stack up more and more tables, it takes more and more time.
This allows to only load the database container at launch.
It's disabled by default.
Possible errors : 
- Database desync if migration is run.

Allow not to reload database on each requests

---

CHANGELOG.md
lib/rom/rails/version.rb
rom-rails.gemspec

Tag for release.
This drops support for Ruby < 2.7, and for Rails < 6.0   
I'm not entirely certain if I should take that as a queue to bump the semver major up to 3.0 or not.  @solnic  do you have a thought there?

tag for a new release
